// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  states: "!^OSOPOOQdOPOOOROP'#Cd'#CdOkOPO'#CdO{OPO,58zO{OPO,58zO!`OPO,59OOROP1G.f1G.fO!jOPO1G.fOROP1G.j1G.j",
  stateData: "!wVOS~RQOZROTSPXSPYSP~XSOYTO~RQOZROXSPYSP[SP~RQOZROTSPXSPYSP[SP~XSOYTO[XO~XSOTSiYSi[Si~",
  goto: "lXPPPPYPPP`XQORSTQPOQURQVSRWT",
  nodeNames: "⚠  ⚠ Number BinaryExpression",
  repeatNodeCount: 0,
  tokenData: "#c~R_X^!Qpq!Qxy!uyz!zz{#P{|#U!Q![#Z#y#z!Q$f$g!Q#BY#BZ!Q$IS$I_!Q$I|$JO!Q$JT$JU!Q$KV$KW!Q&FU&FV!Q~!VYV~X^!Qpq!Q#y#z!Q$f$g!Q#BY#BZ!Q$IS$I_!Q$I|$JO!Q$JT$JU!Q$KV$KW!Q&FU&FV!Q~!zOZ~~#PO[~~#UOX~~#ZOY~~#`PR~!Q![#Z",
  tokenizers: [0],
  specializeTable: 3,
  tokenPrec: 3
})
