// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  states: "!^OSOPOOQdOPOOOROP'#Ce'#CeOkOPO'#CeO{OPO,58{O{OPO,58{O!`OPO,59POROP1G.g1G.gO!jOPO1G.gOROP1G.k1G.k",
  stateData: "!wWOS~SQO[ROUTPYTPZTP~YSOZTO~SQO[ROYTPZTP]TP~SQO[ROUTPYTPZTP]TP~YSOZTO]XO~YSOUTiZTi]Ti~",
  goto: "mYPPPPPZPPPaXQORSTQPOQURQVSRWT",
  nodeNames: "⚠ Expression ⚠ Expression Number BinaryExpression",
  repeatNodeCount: 0,
  tokenData: "#c~R_X^!Qpq!Qxy!uyz!zz{#P{|#U!Q![#Z#y#z!Q$f$g!Q#BY#BZ!Q$IS$I_!Q$I|$JO!Q$JT$JU!Q$KV$KW!Q&FU&FV!Q~!VYW~X^!Qpq!Q#y#z!Q$f$g!Q#BY#BZ!Q$IS$I_!Q$I|$JO!Q$JT$JU!Q$KV$KW!Q&FU&FV!Q~!zO[~~#PO]~~#UOY~~#ZOZ~~#`PS~!Q![#Z",
  tokenizers: [0],
  specializeTable: 3,
  tokenPrec: 3
})
