// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  states: "!WOPOPOOQWOPOOOPOPO'#C`OOOP'#Cb'#CbOPOPO,58zOPOPO,58zO_OPO,58zOOOP1G.f1G.fOiOPO1G.f",
  stateData: "v~RROXQO~VSOWTO~VSOWTOYVO~VSOTSiWSiYSi~",
  goto: "jVPPPPWP^XROQSTQPOQUQQVSRWT",
  nodeNames: "⚠  ⚠ Number BinaryExpression",
  repeatNodeCount: 0,
  tokenData: "!O~RTxybyzgz{l{|q!Q![v~gOX~~lOY~~qOV~~vOW~~{PR~!Q![v",
  tokenizers: [0],
  specializeTable: 0,
  tokenPrec: 0
})
